# Configuración de Base de Datos PostgreSQL (Contenedor db)
spring.datasource.url=jdbc:postgresql://db:5432/appdb
spring.datasource.username=dev
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
