spring.application.name=demo

# Configuración de SQLite (Genera un archivo local 'licoreriadb.db' en la raíz del proyecto)
spring.datasource.url=jdbc:sqlite:licoreriadb.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.datasource.username=usuario
spring.datasource.password=password

# Dialecto de Hibernate compatible con SQLite para Spring Boot 3
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Mantiene la creación y actualización automática de las tablas mediante tus entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true